### ISSUE TITLE
Some question to your Project ;)

### ISSUE THREAD

**Issue by dydyna63** [Sergio00166/pBTE#1]
Hello, great project, great job. I have a question in which part of the code should be changed so that the text displayed on the screen is cut into frames the length of the screen. Now, if a paragraph is long, it can be moved to the right. And if I want the text to always be the length of the screen frame and, additionally, not to be cut at the end, but to display the entire word and, if it is too large, to move to the next line. Can this be done? 
I try to create simple text editor like a small laptop :) 
![20240915_145116](https://github.com/user-attachments/assets/e557ab1b-3d0a-4001-88b5-7df19372325f)
Best regards
Mateusz ;)

**Comment by Sergio00166** [comment]
to do that, It will need to change some a lot of things on how the screen is rendered.
Or to make it symply create one function that executes on each iteration on the main pBTE.py file that checks and modifies the arr to do avoid the line use more space that the screen line lenght by inserting new entries below that one.

**Comment by Sergio00166** [comment]
For example this will be a basic example for the thing you asked for, but it still does not not take into account the full words, it just breaks and adds it to another line

```
def no_split_lines(columns,arr):
    new_arr = []
    for x in arr:
        new_arr += wrap(x, columns)
    return new_arr


if __name__=="__main__":  

    from sys import path
    from os import sep
    # Add the folder to import from here
    path.append(path[0]+sep+"bin")
    from init import *
    from functions import wrap`
    
    # Run the update Thread
    update_thr=Thread(target=updscr_thr)
    run_thread=True; kill=False
    update_thr.start()
    
    while True:
        try:
            # Fix arr when empty
            if len(arr)==0: arr=[""]
            # If status flag is 0 set save text to blank
            if status_st==False: status=saved_df 
            # Get the terminal size
            rows,columns=get_size()
            # Avoid splitting to blocks
            arr = no_split_lines(columns,arr)
            # Call screen updater function
```

**Comment by dydyna63** [comment]
Ooo thx ;) i will try to add function to check if word is cut.

**Comment by dydyna63** [comment]
In which section should I add the battery status function so that it is displayed all the time, not in response to the user's click? for now I placed it in upd_screen, but the function depends on the user's reaction.

**Comment by Sergio00166** [comment]
just create a new thread that redraws that part of the screen with ANSI cursor positionment (in upd_scr.py the var movcr, an then move the cursor to where that text starts and write the new text

**Comment by Sergio00166** [comment]
You can remove the lock from the updscr_thr() in pBTE.py , and change the polling rate to update it automatically and remove the check for if the screen size has changed. And it should be changed also for all files in bin/menus.
I dont know, better keep trying stuff until it works.
